DELETE_ACTION = 'delete'
ADD_ACTION = 'add'
EXPAND_ACTION = 'expand'
CONTRACT_ACTION = 'contract'
ROTATE_ACTION = 'rotate'
REFLECT_ACTION = 'reflect'

ACTIONS = [DELETE_ACTION, ADD_ACTION, EXPAND_ACTION, CONTRACT_ACTION, ROTATE_ACTION, REFLECT_ACTION]
